Repository SoftwyRD/unimate-api, pull requests merged in 2023-02, with the labels that each got.

#11 [FEATURE] Project MVP
  .flake8
  .github/workflows/checks.yml
  .gitignore
  app/app/__init__.py
  app/app/asgi.py
  app/app/settings.py
  app/app/urls.py
  app/app/wsgi.py
  app/core/__init__.py
  app/core/admin.py
  app/core/apps.py
  app/core/models.py
  app/core/tests/__init__.py
  app/core/tests/test_schedule_model.py
  app/core/tests/test_selection_model.py
  app/core/tests/test_selection_section_model.py
  app/core/tests/test_subject_model.py
  app/core/tests/test_user_model.py
  app/core/tests/test_weekday_model.py
  app/manage.py
  app/schedule/__init__.py
  app/schedule/apps.py
  app/schedule/serializers.py
  app/schedule/tests/__init__.py
  app/schedule/tests/test_selection.py
  app/schedule/urls.py
  app/schedule/views.py
  app/subject/__init__.py
  app/subject/apps.py
  app/subject/serializers.py
  app/subject/tests/__init__.py
  app/subject/tests/test_authorized_super_user.py
  app/subject/tests/test_unauthenticated_tests.py
  app/subject/urls.py
  app/subject/views.py
  app/user/__init__.py
  app/user/admin.py
  app/user/apps.py
  app/user/permissions.py
  app/user/serializers.py
  app/user/tests.py
  app/user/urls.py
  app/user/views.py
  requirements.dev.txt
  requirements.txt
Labels: documentation, enhancement

#19 [FEATURE] Renamed schedule app
  app/app/settings.py
  app/app/urls.py
  app/selection/__init__.py
  app/selection/apps.py
  app/selection/serializers.py
  app/selection/tests/__init__.py
  app/selection/tests/test_selection.py
  app/selection/urls.py
  app/selection/views.py
Labels: enhancement

#17 [FEATURE] Added patch method to 'me' view (User app)
  app/user/tests.py
  app/user/views.py
Labels: enhancement

#38 v0.1.0 proposal
  .flake8
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/workflows/checks.yml
  .gitignore
  app/app/__init__.py
  app/app/asgi.py
  app/app/settings.py
  app/app/urls.py
  app/app/wsgi.py
  app/core/__init__.py
  app/core/admin.py
  app/core/apps.py
  app/core/models.py
  app/core/tests/__init__.py
  app/core/tests/test_schedule_model.py
  app/core/tests/test_selection_model.py
  app/core/tests/test_selection_section_model.py
  app/core/tests/test_subject_model.py
  app/core/tests/test_user_model.py
  app/core/tests/test_weekday_model.py
  app/manage.py
  app/selection/__init__.py
  app/selection/apps.py
  app/selection/serializers.py
  app/selection/tests/__init__.py
  app/selection/tests/test_selection.py
  app/selection/urls.py
  app/selection/views.py
  app/subject/__init__.py
  app/subject/apps.py
  app/subject/serializers.py
  app/subject/tests/__init__.py
  app/subject/tests/test_authorized_super_user.py
  app/subject/tests/test_unauthenticated_tests.py
  app/subject/urls.py
  app/subject/views.py
  app/user/__init__.py
  app/user/apps.py
  app/user/permissions.py
  app/user/serializers.py
  app/user/tests.py
  app/user/urls.py
  app/user/views.py
  requirements.dev.txt
  requirements.txt
Labels: documentation, enhancement

#42 Fixed admin panel cors
  app/app/settings.py
Labels: bug

#47 Fixed #44
  app/selection/serializers.py
Labels: bug
